//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutri2Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutri2Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string BuildType {
            get {
                return ResourceManager.GetString("BuildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закуп.
        /// </summary>
        internal static string BuyOperName {
            get {
                return ResourceManager.GetString("BuyOperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server=localhost;database=u1495815_default;port=3306;user=u1495815_mariad;password=a1Az0o9jOBiivd4C;ssl mode=None.
        /// </summary>
        internal static string DbConnectionString {
            get {
                return ResourceManager.GetString("DbConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.5.10-mariadb.
        /// </summary>
        internal static string DbVersionString {
            get {
                return ResourceManager.GetString("DbVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взаиморасчеты.
        /// </summary>
        internal static string MutualPaymentOperName {
            get {
                return ResourceManager.GetString("MutualPaymentOperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не Оплачен.
        /// </summary>
        internal static string NotPaid {
            get {
                return ResourceManager.GetString("NotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расходы.
        /// </summary>
        internal static string OutlayOperName {
            get {
                return ResourceManager.GetString("OutlayOperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплачен.
        /// </summary>
        internal static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передача денег.
        /// </summary>
        internal static string PaymentOperName {
            get {
                return ResourceManager.GetString("PaymentOperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забор товара с точки.
        /// </summary>
        internal static string PointProdGetOperName {
            get {
                return ResourceManager.GetString("PointProdGetOperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to точка сбора.
        /// </summary>
        internal static string PointTypeName {
            get {
                return ResourceManager.GetString("PointTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продажа.
        /// </summary>
        internal static string SellOperName {
            get {
                return ResourceManager.GetString("SellOperName", resourceCulture);
            }
        }
    }
}
